### ISSUE TITLE
Resolved: Very High CPU Usage from Mono PID after latest Radarr container update

### ISSUE THREAD

**Issue by pl77** [linuxserver/docker-radarr#39] opened 2019-03-18 18:44 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

After the latest update my radarr service started running at maximum CPU utilization continuously.  Running top/htop it was apparent that the "mono" PID was the cause of this issue.  After investigating all mono-based containers I narrowed it down to Radarr.  Radarr was recently pulled and updated (within last week) and the error began after that.  

Ubuntu 18.04LTS, 6 core i7 with 64GB RAM, radarr installed on SSD. 

used docker-compose: 

```
version: '3.7'
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
      - radarrconfig:/config
      - movies:/movies
      - kidsmovies:/KidsMovies
      - sab_downloads:/downloads
      - tb1_qb:/qb
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Toronto
      MONO_TLS_PROVIDER: legacy
    expose:
      - "7878"
    networks:
      - webproxy
```

No relevant log messages related to a runaway Mono process.  Last log entry was hours prior to any issue emerging.

No symlinks used...

After some troubleshooting (it took a bit to figure out it was even Radarr causing the problem, as the CPU was being used by the mono PID) I determined that **the "MONO_TLS_PROVIDER: legacy" option was the root of the cpu problems**.  Upon removing that environmental variable and rebooting the radarr container the problem disappeared.

Just providing some feedback in case others (like myself) end up hear searching for MONO RADARR HIGH CPU USAGE DOCKER LINUX or something similar. it's a quick fix, but not immediately apparent.

This should not affect default users, as there is no instruction to enable that environmental variable.  This only affect users who were being impacted by previous errors on earlier builds, such as the following issue:

https://github.com/linuxserver/docker-radarr/issues/17

##  Thanks, team linuxserver.io

And thank you, team linuxserver.io, for the amazing work you all do in giving us these turn-key images.  Much appreciated.

**Comment by aptalca** [comment] 2019-03-18 18:51
Thanks for troubleshooting and confirming that adding the env var was the issue.

Since we don't recommend adding that var in our docs, I'll go ahead and close this issue but we'll keep it in mind if any other user experiences similar issues.

**Closed by aptalca** 2019-03-18 18:51 UTC

**Comment by pl77** [comment] 2019-03-18 19:01
Yes, thanks @aptalca, I meant to suggest imediately closing this in my original post.

I just wanted to make sure it was recorded somewhere so google would pick it up and save someone else a bunch of time tracking it down!

**Comment by danmandle** [comment] 2019-10-07 15:56
I am also experiencing this issue with or without the `MONO_TLS_PROVIDER` flag set. `docker stats` shows that radarr is running 75%+ CPU utilization when idling. I'm running linuxserver/radarr:latest Image ID 3c60aa8e867a, Radarr Ver. 0.2.0.1358 develop. I also have sonarr running and the CPU usage for that container is normal. 

```
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    volumes:
      - /var/docker/radarr:/config
      - /mnt/diskstation/videos/Movies/:/movies
      - /mnt/diskstation/videos/rutorrent:/downloads
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Denver
    ports:
      - 7878
    labels:
      - "traefik.frontend.rule=Host:radarr.docker.df"
    dns: 10.5.0.1
```
`config.xml`
```
<Config>
  <LogLevel>Info</LogLevel>
  <Port>7878</Port>
  <UrlBase></UrlBase>
  <BindAddress>*</BindAddress>
  <SslPort>9898</SslPort>
  <EnableSsl>False</EnableSsl>
  <ApiKey>XXXXXXXXXXXXXXX</ApiKey>
  <AuthenticationMethod>None</AuthenticationMethod>
  <Branch>develop</Branch>
  <LaunchBrowser>True</LaunchBrowser>
  <SslCertHash></SslCertHash>
  <UpdateMechanism>BuiltIn</UpdateMechanism>
</Config>
```

Relevant system info
```
danmandle@docker:~$ sudo lshw -short
H/W path           Device           Class      Description
==========================================================
                                    system     VMware Virtual Platform
/0                                  bus        440BX Desktop Reference Platform
/0/0                                memory     86KiB BIOS
/0/4                                processor  Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
/0/4/15                             memory     16KiB L1 cache
/0/25                               memory     18GiB System Memory
/0/25/0                             memory     16GiB DIMM DRAM EDO
/0/25/1                             memory     2GiB DIMM DRAM EDO
/0/100/10          scsi32           storage    53c1030 PCI-X Fusion-MPT Dual Ultra320 SCSI
/0/100/10/0.0.0    /dev/sda         disk       128GB Virtual disk
/0/100/10/0.0.0/1  /dev/sda1        volume     1023KiB BIOS Boot partition
/0/100/10/0.0.0/2  /dev/sda2        volume     119GiB EXT4 volume
/0/100/10/0.1.0    /dev/sdb         volume     4TiB Virtual disk
/0/1/0.0.0/0/2                      volume     15EiB Windows FAT volume
```

**Comment by aptalca** [comment] 2019-10-07 16:02
Mine's idling at 0.01%-0.13% with occasional spikes to ~45%, whenever it does some processing.

Did you check radarr logs?

Did you modify the config.xml manually?

**Comment by pl77** [comment] 2019-10-07 16:36
In the [related Radarr thread](https://github.com/Radarr/Radarr/issues/3278) they have a couple of suggestions/suspicions you could narrow down:

1. Does this occur after you kill the container and restart the process?
2. Does this occur after a fresh reboot of the server?  Sometimes docker doesn't kill the underlying mono process PIDs and they just keep mucking away chewing up CPU cycles.  Stop any mono containers (Sonarr/Radarr/Lidarr/etc) and then kill any stray mono processes before restarting them and see if that fixes it. 
3. One thing I did was set a `stop_grace_period: 2m` to all my docker containers.  Most don't need nearly that amount of time but it's drastically cut down on the number of file/disk/database errors that I've encountered when I was using the default 10 second 'shut down or die' docker parameter. I have not seen this issue emerge again since I wrote up this issue and made sure the Legacy flag wasn't set.

The only other change I've made to my configuration that isn't really default is relaxing the ulimits so radar has a bit more breathing room.  I can't remember what the original default values are, but I pass these through my docker-compose file:

```yaml
version: '3.7'
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    stop_grace_period: 2m
    ulimits:
      nproc: 500000
      nofile:
        soft: 500000
        hard: 900000
```

They're probably excessively large, but I have a pretty powerful server and I didn't want my apps twiddling their thumbs waiting for a file handle to become available.  Especially important on apps that churn through a pile of tiny XML files.

**Comment by danmandle** [comment] 2019-10-07 20:02
- Radarr logs are uneventful (below). CPU utilization climbed during the two hours I had the container running for, starting at 40-60% and getting up to the 90s. During that time, I did not use Radarr at all, however, Ombi is connected to it but no one was using that either. 
- No, I did not manually edit the config.xml. 
- Happens when the container is running. After I kill the container, system-wide usage peaks to <30% CPU and average load is <0.5 (whereas it was 2.5+ when running Radarr). Mono does not appear in the top 20 processes even with Sonarr running.
- I did try manually killing the mono PID when Radarr was running but it spawned the process again and used the same CPU load.

radarr logs:
```
19-10-7 10:17:28.7|Info|Bootstrap|Starting Radarr - /opt/radarr/Radarr.exe - Version 0.2.0.1358
19-10-7 10:17:29.6|Info|AppFolderInfo|Data directory is being overridden to [/config]
19-10-7 10:17:29.8|Info|Router|Application mode: Interactive
19-10-7 10:17:30.1|Info|MigrationLogger|*** Migrating data source=/config/nzbdrone.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
19-10-7 10:17:30.4|Info|MigrationLogger|*** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
19-10-7 10:17:30.4|Info|OwinHostController|Listening on the following URLs:
19-10-7 10:17:30.4|Info|OwinHostController|  http://*:7878/
19-10-7 10:17:30.6|Info|NancyBootstrapper|Starting NzbDrone API
19-10-7 10:17:32.0|Info|CommandExecutor|Starting 2 threads for tasks.
19-10-7 10:22:02.6|Info|RssSyncService|Starting RSS Sync
19-10-7 10:22:04.8|Info|DownloadDecisionMaker|Processing 256 releases
19-10-7 10:23:31.6|Info|RssSyncService|RSS Sync Completed. Reports found: 256, Reports grabbed: 0
19-10-7 10:39:04.2|Info|PreDBService|Starting PreDB Sync
19-10-7 10:39:04.2|Info|NetImportSearchService|No lists are enabled for auto-import.
19-10-7 11:23:36.9|Info|RssSyncService|Starting RSS Sync
19-10-7 11:23:39.4|Info|DownloadDecisionMaker|Processing 267 releases
19-10-7 11:24:34.8|Info|RssSyncService|RSS Sync Completed. Reports found: 267, Reports grabbed: 0
19-10-7 11:39:09.5|Info|PreDBService|Starting PreDB Sync
19-10-7 11:39:09.6|Info|NetImportSearchService|No lists are enabled for auto-import.
19-10-7 12:24:41.8|Info|RssSyncService|Starting RSS Sync
19-10-7 12:24:42.8|Info|DownloadDecisionMaker|Processing 295 releases
19-10-7 12:25:10.7|Info|RssSyncService|RSS Sync Completed. Reports found: 295, Reports grabbed: 0
19-10-7 12:39:12.2|Info|PreDBService|Starting PreDB Sync
19-10-7 12:39:12.3|Info|NetImportSearchService|No lists are enabled for auto-import.
19-10-7 13:25:13.5|Info|RssSyncService|Starting RSS Sync
19-10-7 13:25:14.2|Info|DownloadDecisionMaker|Processing 288 releases
19-10-7 13:25:41.6|Info|RssSyncService|RSS Sync Completed. Reports found: 288, Reports grabbed: 0
```

**Comment by j0nnymoe** [comment] 2019-10-07 20:22
@pl77 as you're the OP of this issue, do you suffer from this issue now?

**Comment by j0nnymoe** [comment] 2019-10-07 20:50
@pl77 ah cool, was just checking :)

I fear that I suspect this issue could be related to @danmandle running this on synology hardware. Only reason I say this is we constantly see oddities with our containers running on synology hardware and since no one within the team runs/owns this hardware, support for it is "best effort".

@danmandle please could you try @pl77's docker-compose with your setup and see how you get on?

**Comment by pl77** [comment] 2019-10-07 21:02
@j0nnymoe one thing I encountered last week that might be applicable was with Lidarr.  I hadn't run that container in probably a year, so when I spun it up it ran like a dog.  Every page load took forever. 

When I spun it down and peeked inside the database it was full of gibberish and the WAL files were about 10x the size of the actual database.  Once I deleted the database and started fresh it spun up and ran perfectly.  

I wonder if a final hail mary might be deleting the actual sqlite databases and rebuilding them from scratch?  Perhaps there was a database migration that wasn't automatically applied and it's causing issues?  🤷‍♂

**Comment by danmandle** [comment] 2019-10-07 22:10
@pl77 makes it really hard to respond when you keep editing your post :-P

@j0nnymoe I'm not running this on a NAS. It's running on Ubuntu on ESXi. See [this post](https://github.com/linuxserver/docker-radarr/issues/39#issuecomment-539081962) for system info. 

- I removed three empty files but unfortunately that had no impact. 
- I blew everything away and am starting from scratch. Normal CPU usage so far. Importing movies now and will configure after. Will report back at what point CPU usage spikes again.

**Comment by pl77** [comment] 2019-10-07 22:12
Lol, sorry @danmandle.  Usually I go weeks or months between a post and a response on github so I've gotten a little complacent about edits.  I promise I won't edit this post!

**Comment by j0nnymoe** [comment] 2019-10-07 22:19
@danmandle apologies, I saw `diskstation/` and assumed that was syno's setup.
Hopefully you've managed to fix the issue now.

**Comment by danmandle** [comment] 2019-10-07 22:54
@j0nnymoe I'm not sure I would call wiping everything and starting over a fix, but so far it's behaving itself.

**Comment by acahir** [comment] 2019-12-14 01:28
I'm seeing the same thing on a new install of radarr, and yes it is running on a Synology. Mono process in the radarr container is running 95+% cpu in container. (only shows as 25% from docker side since only on one core). Checked for the MONO_TLS_PROVIDER flag, but it's not set. 

Radarr isn't processing anything, and so far haven't found anything in the logs that would point at what it's doing.

I've restarted the container, radarr, etc. Haven't figured it out yet, but if I track it down, I'll share back here.

**Comment by KillerKelvUK** [comment] 2020-04-05 19:21
So just got a Synology DS1019+ and moved radarr into a docker container and noticed this issue.  2nd google link here got me to the work-around...

https://github.com/Radarr/Radarr/issues/3278#issuecomment-566087989

Basically don't use radarr's webUI to restart radarr, user the docker controls within the Synology web management UI...hack for sure but radarr CPU util went from +20% to <1%.

**Comment by acahir** [comment] 2020-04-05 21:03
@KillerKelvUK Let me know if the CPU usage stays that way. I saw after restarting it was low, but by the next day it was back up. It hasn't impacted anything so I haven't worried about it too much.

**Comment by KillerKelvUK** [comment] 2020-04-06 08:25
@acahir so 13 hours in and radarr is showing CPU at 0.08% which seems to be its resting value.

**Comment by KillerKelvUK** [comment] 2020-04-07 10:11
@acahir so 2+ days now and still stable CPU currently reporting 0.1% utilisation so this hack looks good.

**Comment by acahir** [comment] 2020-04-07 13:34
@KillerKelvUK appreciate the update, thanks, I'll give it a go later today.

**Comment by nsar1907** [comment] 2020-05-04 22:21
im having the same problem on my nas 218+ and it didnt work that restarting it on docker.

did you find a way to fix it ?

**Comment by acahir** [comment] 2020-05-04 23:35
I'm seeing under 1% CPU usage now too for weeks. 

This fix also explains why sometimes in the past for me it was fine and sometimes it was high. Prob had restarted through webUI without realizing it.

**Comment by nsar1907** [comment] 2020-05-04 23:37
> I'm seeing under 1% CPU usage now too for weeks.
> 
> This fix also explains why sometimes in the past for me it was fine and sometimes it was high. Prob had restarted through webUI without realizing it.

so u just restart it on docker and the problem is gone?

**Comment by acahir** [comment] 2020-05-05 00:19
Worked for me
