### ISSUE TITLE
Moving and renaming fails

### ISSUE THREAD

**Issue by mlix11** [linuxserver/docker-radarr#79] opened 2020-01-07 14:06 UTC
## Expected Behavior
Radarr finds, renames and moves files to expected location provided by the volumes path.

## Current Behavior
Radarr searches on the wrong place to find the already downloaded movie. 
`Import failed, path does not exist or is not accessible by Radarr: /config/Downloads/complete/family.movie`

## Steps to Reproduce
1. Running radarr with docker-compose
2. Add movie to radarr
3. Download it with a download client to `/var/nfs/general/media/Data/Downloads/complete/`
4. After the download radarr is not able to find the downloaded file, because it is looking for `/config/Downloads` not `/downloads`

## Environment
**OS:** Rasbian Buster      
**CPU architecture:** armv7l     
**How docker service was installed:**  
`curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh`

## Command used to create docker container (run/create/compose/screenshot)
`docker-compose up -d`

```
version: '3'
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Berlin
      - UMASK_SET=022
    volumes:
      - /var/nfs/general/media/Radarr_Data/:/config
      - /var/nfs/general/media/movies/:/movies
      - /var/nfs/general/media/Data/Downloads/complete/:/downloads
    ports:
      - 7878:7878
    network_mode: "host"
    restart: unless-stopped
```
## Temporary solution:
`mkdir config/Downloads && ln -s /downloads Downloads/complete`

**Comment by aptalca** [comment] 2020-01-07 15:01
Your downloader is sending the download path to radarr as `/config/Downloads`. Either set the `/downloads` mapping the same throughout radarr and the downloader so they both use the same paths, or set remote path mapping in radarr gui settings.

Feel free to drop by our discord or forum for further help.

Closing this as it is not a bug report.

**Closed by aptalca** 2020-01-07 15:01 UTC
