### ISSUE TITLE
Radarr v3 doesn't start on armhf (Raspberry Pi 4 - Raspbian Buster)

### ISSUE THREAD

**Issue by mvantoor** [linuxserver/docker-radarr#121] opened 2020-12-01 18:26 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Upgraded to a recent 'latest' version (3.0.0.4204-ls85) of the Radarr docker image while coming from a couple of months old 'latest' version (v0.2.0.x).

------------------------------

## Expected Behavior
Radarr service is running after starting the container.

## Current Behavior
Radarr service is not running after starting the container

## Steps to Reproduce
1. Pull 'latest' version (3.0.0.4204-ls85) of Radarr docker image and start container based on this version
2. Open browser and visit the Radarr website on `http://<rpi4-ip-address>:7878`
3. Browser displays message website cannot be opened or reached

## Environment
**OS:** "Raspbian GNU/Linux 10 (buster)
**CPU architecture:** arm32 (armv7l)
**How docker service was installed:**
Followed installation instructions for Debian on docs.docker.com (https://docs.docker.com/engine/install/debian/)

## Command used to create docker container (run/create/compose/screenshot)
```
docker create \
  --name=radarr \
  --network=downloadbox \
  --restart=unless-stopped \
  -e PUID=1000 \
  -e PGID=995 \
  -e TZ=Europe/Amsterdam \
  -p 7878:7878 \
  -v /mnt/usbhdd/radarr/config:/config \
  -v /mnt/usbhdd/radarr/movies:/movies \
  -v /mnt/usbhdd/nzbget/downloads:/downloads \
  ghcr.io/linuxserver/radarr
```

## Docker logs
```
[s6-init] making user provided files a0vailable at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    995
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by Roxedus** [comment] 2020-12-01 18:28
Dupe of #118 
https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal

**Closed** 2020-12-01 18:28 UTC
