### ISSUE TITLE
Radarr process is not starting on QNAP

### ISSUE THREAD

**Issue by eevlogiev** [linuxserver/docker-radarr#130] opened 2021-01-11 15:07 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Folks,
I've been using Radarr for quite some time on my QNAP TS-231P2 but because of the dependencies to Mono I am now switching to the Docker version. I am deploying the container using QNAP's Container Station (did the same already for Jackett, Bazarr, etc.). The radarr process seems to be starting but there is nothing listening on port 7878.

## Current Behavior
The radarr process seems to be starting but there is nothing listening on port 7878. I am using "host" network configuration where the container is sharing same IP/port as the host itself.

## Steps to Reproduce
```
[~] # netstat -lt | grep 7878
[~] # ps aux | grep -i radarr
 6455 admin        72 S   s6-supervise radarr 
10930 911        3124 R   /app/radarr/bin/Radarr -nobrowser -data=/config 
10933 admin       344 S   grep -i radarr 
[~] # 
```

## Environment
**OS:** QNAP QTS 4.5.1.1.1540 (2021/01/07)
**CPU architecture:** arm32
**How docker service was installed:**
Installed via Container Station on QNAP TS-231P2

## Command used to create docker container (run/create/compose/screenshot)
<img width="860" alt="Screenshot 2021-01-11 at 16 59 52" src="https://user-images.githubusercontent.com/27862102/104198549-050f0a80-542f-11eb-8aa2-e36c5987a184.png">

## Docker logs
```[~] # docker logs radarr
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
``

**Comment by Roxedus** [comment] 2021-01-11 15:09
Dupe of #112

**Closed by Roxedus** 2021-01-11 15:09 UTC

**Comment by eevlogiev** [comment] 2021-01-11 15:12
@Roxedus ,
I checked #112 but I don't use any custom scripts. I am just trying to start the default linuxserver container. Could you please put some more light on the resolution?

Thanks and appreciate!

**Comment by Roxedus** [comment] 2021-01-11 15:13
I linked the wrong issue, I meant to link #122

**Comment by aptalca** [comment] 2021-01-11 15:19
Other issues are: 
- There is no reason to do host networking. Use bridge (or user defined bridge if reverse proxying)
- Set the correct PUID/PGID

**Comment by eevlogiev** [comment] 2021-01-11 17:12
Thank you both. Noted.
